export type AuditAction =
  | 'visitor_created'
  | 'visitor_updated'
  | 'visitor_anonymised'
  | 'visit_scheduled'
  | 'visit_amended'
  | 'visit_cancelled'
  | 'visit_checked_in'
  | 'visit_departed'
  | 'visit_signed_out'
  | 'induction_completed'
  | 'document_accepted'
  | 'pre_approval_requested'
  | 'pre_approval_approved'
  | 'pre_approval_rejected'
  | 'pre_approval_revoked'
  | 'deny_list_added'
  | 'deny_list_updated'
  | 'deny_list_removed'
  | 'deny_list_check_blocked'
  | 'notification_sent'
  | 'notification_acknowledged'
  | 'escalation_triggered'
  | 'evacuation_activated'
  | 'evacuation_closed'
  | 'user_created'
  | 'user_updated'
  | 'user_deactivated'
  | 'site_config_updated'
  | 'hs_content_published'

export type AuditEntityType =
  | 'visitor'
  | 'visit'
  | 'user'
  | 'site'
  | 'pre_approval'
  | 'deny_list'
  | 'notification'
  | 'evacuation_event'
  | 'induction_record'
  | 'visit_document'

export const INDUCTION_VALIDITY_DAYS = 28
